var document = new ActiveXObject("MSXML.DOMDocument");
var rootElem = document.createElement('movies_catalog');
document.appendChild(rootElem);
var childElem= document.createElement('catalog_name');
rootElem.appendChild(childElem);
var text= document.createTextNode('Филмов каталог');
childElem.appendChild(text);
var childElem1= document.createElement('movies');
rootElem.appendChild(childElem1);
var childElem2= document.createElement('movie');
childElem1.appendChild(childElem2);
childElem2.setAttribute('id', '1');
childElem2.setAttribute('type', 'feature');
var childElem3= document.createElement('movie_name');
childElem2.appendChild(childElem3);
var text= document.createTextNode('2012');
childElem3.appendChild(text);
var childElem4= document.createElement('genre');
childElem2.appendChild(childElem4);
var text= document.createTextNode('Екшън, Трилър, Фантастика');
childElem4.appendChild(text);
var childElem5= document.createElement('director');
childElem2.appendChild(childElem5);
var text= document.createTextNode('Роланд Емерих');
childElem5.appendChild(text);
var childElem6= document.createElement('actors');
childElem2.appendChild(childElem6);
var text= document.createTextNode('Джон Кюсак, Аманда Пийт, Оливър Плат, Томас МакКарти, Дани Глоувър, Чиуетел Еджиофор, Танди Нютън, Уди Харелсън и др.');
childElem6.appendChild(text);
var childElem7= document.createElement('country');
childElem2.appendChild(childElem7);
var text= document.createTextNode('САЩ, Канада');
childElem7.appendChild(text);
var childElem8= document.createElement('year');
childElem2.appendChild(childElem8);
var text= document.createTextNode('2009г');
childElem8.appendChild(text);
var childElem9= document.createElement('duration');
childElem2.appendChild(childElem9);
var text= document.createTextNode('158');
childElem9.appendChild(text);
childElem9.setAttribute('measure', 'минути');

var childElem2= document.createElement('movie');
childElem1.appendChild(childElem2);
childElem2.setAttribute('id', '2');
childElem2.setAttribute('type', 'feature');
var childElem3= document.createElement('movie_name');
childElem2.appendChild(childElem3);
var text= document.createTextNode('Здрач');
childElem3.appendChild(text);
var childElem4= document.createElement('genre');
childElem2.appendChild(childElem4);
var text= document.createTextNode('Драма, Фентъзи, Трилър');
childElem4.appendChild(text);
var childElem5= document.createElement('director');
childElem2.appendChild(childElem5);
var text= document.createTextNode('Катрин Хардуик');
childElem5.appendChild(text);
var childElem6= document.createElement('actors');
childElem2.appendChild(childElem6);
var text= document.createTextNode('Кристън Стюарт, Робърт Патинсън, Майкъл Уелч, Келлан Луц, Питър Фачинели и др.');
childElem6.appendChild(text);
var childElem7= document.createElement('country');
childElem2.appendChild(childElem7);
var text= document.createTextNode('САЩ');
childElem7.appendChild(text);
var childElem8= document.createElement('year');
childElem2.appendChild(childElem8);
var text= document.createTextNode('2009г');
childElem8.appendChild(text);
var childElem9= document.createElement('duration');
childElem2.appendChild(childElem9);
var text= document.createTextNode('122');
childElem9.appendChild(text);
childElem9.setAttribute('measure', 'минути');

var childElem2= document.createElement('movie');
childElem1.appendChild(childElem2);
childElem2.setAttribute('id', '3');
childElem2.setAttribute('type', 'series');
var childElem3= document.createElement('movie_name');
childElem2.appendChild(childElem3);
var text= document.createTextNode('Клюкарката');
childElem3.appendChild(text);
var childElem4= document.createElement('genre');
childElem2.appendChild(childElem4);
var text= document.createTextNode('Трилър');
childElem4.appendChild(text);
var childElem5= document.createElement('director');
childElem2.appendChild(childElem5);
var text= document.createTextNode('Джош Щварц, Стефани Севич');
childElem5.appendChild(text);
var childElem6= document.createElement('actors');
childElem2.appendChild(childElem6);
var text= document.createTextNode('Блеик Лавли, Лейтон Местер, Пен Бадглей, Чеис Крауфорд, Тейлър Момсен');
childElem6.appendChild(text);
var childElem7= document.createElement('country');
childElem2.appendChild(childElem7);
var text= document.createTextNode('САЩ');
childElem7.appendChild(text);
var childElem8= document.createElement('year');
childElem2.appendChild(childElem8);
var text= document.createTextNode('2008г');
childElem8.appendChild(text);
var childElem9= document.createElement('duration');
childElem2.appendChild(childElem9);
var text= document.createTextNode('44');
childElem9.appendChild(text);
childElem9.setAttribute('measure', 'минути');

var childElem2= document.createElement('movie');
childElem1.appendChild(childElem2);
childElem2.setAttribute('id', '4');
childElem2.setAttribute('type', 'feature');
var childElem3= document.createElement('movie_name');
childElem2.appendChild(childElem3);
var text= document.createTextNode('Зеленият път');
childElem3.appendChild(text);
var childElem4= document.createElement('genre');
childElem2.appendChild(childElem4);
var text= document.createTextNode('Драма, Криминален');
childElem4.appendChild(text);
var childElem5= document.createElement('director');
childElem2.appendChild(childElem5);
var text= document.createTextNode('Франк Дарабонт');
childElem5.appendChild(text);
var childElem6= document.createElement('actors');
childElem2.appendChild(childElem6);
var text= document.createTextNode('Том Ханкс, Дейвид Морс, Майкъл Кларк Дънкан, Бони Хънт, Джеймс Кромуел и др.');
childElem6.appendChild(text);
var childElem7= document.createElement('country');
childElem2.appendChild(childElem7);
var text= document.createTextNode('САЩ');
childElem7.appendChild(text);
var childElem8= document.createElement('year');
childElem2.appendChild(childElem8);
var text= document.createTextNode('1999г');
childElem8.appendChild(text);
var childElem9= document.createElement('duration');
childElem2.appendChild(childElem9);
var text= document.createTextNode('188');
childElem9.appendChild(text);
childElem9.setAttribute('measure', 'минути');

var childElem2= document.createElement('movie');
childElem1.appendChild(childElem2);
childElem2.setAttribute('id', '5');
childElem2.setAttribute('type', 'feature');
var childElem3= document.createElement('movie_name');
childElem2.appendChild(childElem3);
var text= document.createTextNode('Послепис: Обичам те');
childElem3.appendChild(text);
var childElem4= document.createElement('genre');
childElem2.appendChild(childElem4);
var text= document.createTextNode('Драма, Романтичен');
childElem4.appendChild(text);
var childElem5= document.createElement('director');
childElem2.appendChild(childElem5);
var text= document.createTextNode('Ричард Лагравенес');
childElem5.appendChild(text);
var childElem6= document.createElement('actors');
childElem2.appendChild(childElem6);
var text= document.createTextNode('Хилари Суонк, Джерард Бътлър, Лиса Кудроу, Джина Гершон, Джеймс Марстърс и други');
childElem6.appendChild(text);
var childElem7= document.createElement('country');
childElem2.appendChild(childElem7);
var text= document.createTextNode('САЩ');
childElem7.appendChild(text);
var childElem8= document.createElement('year');
childElem2.appendChild(childElem8);
var text= document.createTextNode('2007г');
childElem8.appendChild(text);
var childElem9= document.createElement('duration');
childElem2.appendChild(childElem9);
var text= document.createTextNode('126');
childElem9.appendChild(text);
childElem9.setAttribute('measure', 'минути');

var childElem2= document.createElement('movie');
childElem1.appendChild(childElem2);
childElem2.setAttribute('id', '6');
childElem2.setAttribute('type', 'feature');
var childElem3= document.createElement('movie_name');
childElem2.appendChild(childElem3);
var text= document.createTextNode('Тетрадката');
childElem3.appendChild(text);
var childElem4= document.createElement('genre');
childElem2.appendChild(childElem4);
var text= document.createTextNode('Драма, Романтичен');
childElem4.appendChild(text);
var childElem5= document.createElement('director');
childElem2.appendChild(childElem5);
var text= document.createTextNode('Ник Касаветис');
childElem5.appendChild(text);
var childElem6= document.createElement('actors');
childElem2.appendChild(childElem6);
var text= document.createTextNode('Рейчъл Макадамс, Сам Шепърд, Райън Гослинг,  Джеймс Гарнър, Джина Роуландс, Джеймс Марсдън');
childElem6.appendChild(text);
var childElem7= document.createElement('country');
childElem2.appendChild(childElem7);
var text= document.createTextNode('САЩ, Португалия');
childElem7.appendChild(text);
var childElem8= document.createElement('year');
childElem2.appendChild(childElem8);
var text= document.createTextNode('2004г');
childElem8.appendChild(text);
var childElem9= document.createElement('duration');
childElem2.appendChild(childElem9);
var text= document.createTextNode('119');
childElem9.appendChild(text);
childElem9.setAttribute('measure', 'минути');

var childElem10= document.createElement('producers');
rootElem.appendChild(childElem10);
var childElem11= document.createElement('producer');
childElem10.appendChild(childElem11);
childElem11.setAttribute('gender', 'male');
childElem11.setAttribute('family_status', 'married');
var childElem12= document.createElement('first_name');
childElem11.appendChild(childElem12);
var text= document.createTextNode('Лари');
childElem12.appendChild(text);
var childElem13= document.createElement('last_name');
childElem11.appendChild(childElem13);
var text= document.createTextNode('Джей Франко');
childElem13.appendChild(text);
var childElem14= document.createElement('films_produced');
childElem11.appendChild(childElem14);
var text= document.createTextNode('2012, Батман в началото, Големи неприятности в Малкия Китай,  Принцът на мрака и др.');
childElem14.appendChild(text);
var childElem15= document.createElement('date_of_birth');
childElem11.appendChild(childElem15);
var text= document.createTextNode('5 Април, 1949г.');
childElem15.appendChild(text);

var childElem11= document.createElement('producer');
childElem10.appendChild(childElem11);
childElem11.setAttribute('gender', 'male');
childElem11.setAttribute('family_status', 'married');
var childElem12= document.createElement('first_name');
childElem11.appendChild(childElem12);
var text= document.createTextNode('Джордж');
childElem12.appendChild(text);
var childElem13= document.createElement('last_name');
childElem11.appendChild(childElem13);
var text= document.createTextNode('Лукас');
childElem13.appendChild(text);
var childElem14= document.createElement('films_produced');
childElem11.appendChild(childElem14);
var text= document.createTextNode('Зеленият път, Междузвездни войни, Американски графити и др. ');
childElem14.appendChild(text);
var childElem15= document.createElement('date_of_birth');
childElem11.appendChild(childElem15);
var text= document.createTextNode('14 Май 1944г.');
childElem15.appendChild(text);

var childElem11= document.createElement('producer');
childElem10.appendChild(childElem11);
childElem11.setAttribute('gender', 'male');
childElem11.setAttribute('family_status', 'married');
var childElem12= document.createElement('first_name');
childElem11.appendChild(childElem12);
var text= document.createTextNode('Ридли');
childElem12.appendChild(text);
var childElem13= document.createElement('last_name');
childElem11.appendChild(childElem13);
var text= document.createTextNode('Скот');
childElem13.appendChild(text);
var childElem14= document.createElement('films_produced');
childElem11.appendChild(childElem14);
var text= document.createTextNode('Гладиатор, Небесно царство,Телма и Луиз, Ханибал   и др.  ');
childElem14.appendChild(text);
var childElem15= document.createElement('date_of_birth');
childElem11.appendChild(childElem15);
var text= document.createTextNode('30 Ноември 1937г.');
childElem15.appendChild(text);

var childElem11= document.createElement('producer');
childElem10.appendChild(childElem11);
childElem11.setAttribute('gender', 'female');
var childElem12= document.createElement('first_name');
childElem11.setAttribute('family_status', 'unmarried');
childElem11.appendChild(childElem12);
var text= document.createTextNode('Дрю');
childElem12.appendChild(text);
var childElem13= document.createElement('last_name');
childElem11.appendChild(childElem13);
var text= document.createTextNode('Баримор');
childElem13.appendChild(text);
var childElem14= document.createElement('films_produced');
childElem11.appendChild(childElem14);
var text= document.createTextNode('Целуни ме, Дони Дарко, Дуплекс, Ангелите на Чарли и др. ');
childElem14.appendChild(text);
var childElem15= document.createElement('date_of_birth');
childElem11.appendChild(childElem15);
var text= document.createTextNode('22 февруари 1975г.');
childElem15.appendChild(text);


var childElem16= document.createElement('studios');
rootElem.appendChild(childElem16);
var childElem17= document.createElement('studio');
childElem16.appendChild(childElem17);
var childElem18= document.createElement('studio_name');
childElem17.appendChild(childElem18);
var text= document.createTextNode('20th Century Fox');
childElem18.appendChild(text);
var childElem19= document.createElement('founded');
childElem17.appendChild(childElem19);
var text= document.createTextNode('1935г.');
childElem19.appendChild(text);
var childElem20= document.createElement('headquarters');
childElem17.appendChild(childElem20);
var text= document.createTextNode('ЛA, Калифорния.');
childElem20.appendChild(text);
var childElem21= document.createElement('owner');
childElem17.appendChild(childElem21);
var text= document.createTextNode('News Corporation');
childElem21.appendChild(text);

var childElem17= document.createElement('studio');
childElem16.appendChild(childElem17);
var childElem18= document.createElement('studio_name');
childElem17.appendChild(childElem18);
var text= document.createTextNode('Warner Bros. Pictures');
childElem18.appendChild(text);
var childElem19= document.createElement('founded');
childElem17.appendChild(childElem19);
var text= document.createTextNode('1918г.');
childElem19.appendChild(text);
var childElem20= document.createElement('headquarters');
childElem17.appendChild(childElem20);
var text= document.createTextNode('Бурбанк, Калифорния');
childElem20.appendChild(text);
var childElem21= document.createElement('owner');
childElem17.appendChild(childElem21);
var text= document.createTextNode('Бари Меър, Алан Ф. Хорн');
childElem21.appendChild(text);

var childElem17= document.createElement('studio');
childElem16.appendChild(childElem17);
var childElem18= document.createElement('studio_name');
childElem17.appendChild(childElem18);
var text= document.createTextNode('Universal Studios');
childElem18.appendChild(text);
var childElem19= document.createElement('founded');
childElem17.appendChild(childElem19);
var text= document.createTextNode('1912г.');
childElem19.appendChild(text);
var childElem20= document.createElement('headquarters');
childElem17.appendChild(childElem20);
var text= document.createTextNode('Калифорния');
childElem20.appendChild(text);
var childElem21= document.createElement('owner');
childElem17.appendChild(childElem21);
var text= document.createTextNode('General Electric');
childElem21.appendChild(text);


document.save('Movies8.xml');